### PR TITLE
fix broken stdfile backend

### LINKED ISSUE #86: fix broken stdfile backend
After re-organization turned out we weren't properly testing this and it has missing includes.

### PR DESCRIPTION
**Pull request by nmm0**
Fixes #86

### CODE REVIEW

File: examples/SimpleFileCheckpoint.cpp [hunk 1]
```diff
@@ -46,16 +46,16 @@
...
+#include <resilience/context/Context.hpp>
+#include <resilience/backend/StdFileBackend.hpp>
 #include <resilience/AutomaticCheckpoint.hpp>
 
 int
 main( int argc, char **argv )
 {
   Kokkos::initialize( argc, argv );
   {
-    auto ctx = KokkosResilience::make_context( "checkpoint.data", "config_file.json" );
```
Comment (nmm0) [inline examples/SimpleFileCheckpoint.cpp:58]: Now included in the config file so we have less overloads of `make_context`

File: examples/CMakeLists.txt [hunk 2]
```diff
@@ -38,7 +38,6 @@ if (KR_ENABLE_VELOC)
     add_example(ping_pong SOURCES ping_pong.cpp RESOURCES config.json veloc_test.cfg)
 endif()
 
-if (KR_ENABLE_STDFILE)
```
Comment (nmm0) [inline examples/CMakeLists.txt:41]: `KR_ENABLE_STDFILE` is now on permenantly and the cmake define goes away

File: src/resilience/context/Context.cpp [hunk 3]
```diff
@@ -70,7 +74,48 @@ namespace KokkosResilience
...
+
+#ifdef KR_ENABLE_MPI_CONTEXT
+  std::unique_ptr< ContextBase >
+  make_context( MPI_Comm comm, const std::string &config )
+  {
+    return make_context( comm, Config{ config } );
+  }
+
+  std::unique_ptr< ContextBase >
+  make_context( MPI_Comm comm, const Config &cfg )
```
Comment (nmm0) [inline src/resilience/context/Context.cpp:103]: moved these over from MPIContext.cpp

File: tests/TestOpenMPResilientExecution.cpp [hunk 4]
```diff
@@ -111,7 +111,7 @@ TEST(TestResOpenMP, TestResilientForDouble)
   //Initialize y vector on host using parallel_for, increment a counter for data accesses.
   Kokkos::parallel_for( range_policy (0, N), KOKKOS_LAMBDA ( const int i) {
     y ( i ) = i;
-    Kokkos::atomic_increment(&counter(0));
+    Kokkos::atomic_inc(&counter(0));
```
Comment (nmm0) [inline tests/TestOpenMPResilientExecution.cpp:114]: Fixes from Kokkos deprecation

File: examples/benchmark_multiviews.cpp [hunk 5]
```diff
@@ -45,7 +45,7 @@
 #include <Kokkos_Core.hpp>
 #include <resilience/Resilience.hpp>
 #include <random>
-#include <resilience/CheckpointFilter.hpp>
+#include <resilience/context/CheckpointFilter.hpp>
```
Comment (Matthew-Whitlock) [inline examples/benchmark_multiviews.cpp:48]: I think this should be included already by Resilience.hpp
```suggestion
```

File: src/resilience/context/Context.cpp [hunk 6]
```diff
@@ -70,7 +74,48 @@ namespace KokkosResilience
...
+           return std::make_unique<StdFileContext<StdFileBackend> >(cfg);
+         }}};
+  
+    auto pos = backends.find(cfg["backend"].as<std::string>());
+    if (pos == backends.end()) return {};
+  
+    return pos->second();
+  }
+
+#ifdef KR_ENABLE_MPI_CONTEXT
```
Comment (Matthew-Whitlock) [inline src/resilience/context/Context.cpp:95]: This will be simpler once the backends are virtual, but for now:
```suggestion
#if defined(KR_ENABLE_MPI_CONTEXT) && defined(KR_ENABLE_VELOC_BACKEND)
```

File: src/resilience/context/MPIContext.cpp [hunk 7]
```diff
@@ -45,24 +45,3 @@
 #include <unordered_map>
 #include <functional>
 
-namespace KokkosResilience {
```
Comment (Matthew-Whitlock) [inline src/resilience/context/MPIContext.cpp:48]: Should we just remove this file?

File: src/resilience/context/Context.cpp [hunk 8]
```diff
@@ -70,7 +74,48 @@ namespace KokkosResilience
   std::unique_ptr< ContextBase >
   make_context( const std::string &config )
```
Comment (Matthew-Whitlock) [inline src/resilience/context/Context.cpp:75]: Since filenames are now in the config file (which I support), we need a new way to get unique filenames per process. We could just have the user pass a pid in, then the StdFileContext can append ".<pid>" to the filename being passed to the StdFileBackend
```suggestion
  make_context( const int process_id, const std::string &config )
```

Edit: I just caught that you can just edit the Config object to set a unique filename, so this isn't totally necessary.

File: src/resilience/context/StdFileContext.hpp [hunk 9]
```diff
@@ -50,8 +50,8 @@ namespace KokkosResilience {
 template <typename Backend>
 class StdFileContext : public ContextBase {
  public:
-  explicit StdFileContext(std::string const &filename, Config &cfg)
-      : ContextBase(cfg), m_filename(filename), m_backend(*this, filename) {}
+  explicit StdFileContext(const Config &cfg)
+      : ContextBase(cfg), m_filename(get_filename(cfg)), m_backend(*this, m_filename) {}
```
Comment (Matthew-Whitlock) [inline src/resilience/context/StdFileContext.hpp:54]:
```suggestion
  explicit StdFileContext(const int pid, const Config &cfg)
      : ContextBase(cfg), m_pid(pid), m_filename(get_filename(cfg)), m_backend(*this, m_filename) {}
```

File: src/resilience/context/StdFileContext.hpp [hunk 10]
```diff
@@ -119,6 +119,11 @@ class StdFileContext : public ContextBase {
   }
 
  private:
+
+  static std::string get_filename(const Config &cfg) {
+    return cfg["backends"]["stdfile"]["file"].as<std::string>();
```
Comment (Matthew-Whitlock) [inline src/resilience/context/StdFileContext.hpp:124]:
```suggestion
    return cfg["backends"]["stdfile"]["file"].as<std::string>() + "." + std::to_string(m_pid);
```

File: src/resilience/context/StdFileContext.hpp [hunk 11]
```diff
@@ -119,6 +119,11 @@ class StdFileContext : public ContextBase {
...
+  }
+
```
Comment (Matthew-Whitlock) [inline src/resilience/context/StdFileContext.hpp:126]:
```suggestion

  int m_pid;
```

File: src/resilience/context/StdFileContext.hpp (hunk 9 above)
Comment (Matthew-Whitlock) [inline src/resilience/context/StdFileContext.hpp:54]:
```suggestion
  explicit StdFileContext(const int pid, const Config &cfg)
      : ContextBase(cfg), m_pid(pid), m_filename(get_filename(cfg)), m_backend(*this, m_filename) {}
```

File: tests/TestStdFileBackend.cpp [hunk 12]
```diff
@@ -137,15 +138,16 @@ TYPED_TEST( TestStdFileBackend, veloc_mem )
   using namespace std::string_literals;
   KokkosResilience::Config cfg;
   cfg["backend"].set( "stdfile"s );
-  //cfg["backends"]["stdfile"]["config"].set( KR_TEST_DATADIR "/stdfile_test.cfg"s );
-  KokkosResilience::StdFileContext< KokkosResilience::StdFileBackend > ctx( KR_TEST_DATADIR "/stdfile/stdfile_test"s, cfg );
+  cfg["backends"]["stdfile"]["file"].set( KR_TEST_DATADIR "/stdfile/stdfile_test"s );
```
Comment (Matthew-Whitlock) [inline tests/TestStdFileBackend.cpp:141]: Whoops, I made the comments about the pid before I saw this approach for setting the checkpoint file at runtime. If it's easier, we can just let this be the recommended way to set individual filenames for now until the other changes are merged in.

**Review by Matthew-Whitlock — CHANGES_REQUESTED** [review]
The only really necessary changes are the ifdef guards in Context.cpp

File: src/resilience/context/Context.cpp (hunk 6 above)
Comment (nmm0) [reply src/resilience/context/Context.cpp:95]: I decided to move thse down into the function body -- basically it's still valid to call make_context but it will return a nullptr as there would not be any supported MPI backends if VeloC is not enabled

File: src/resilience/context/MPIContext.cpp (hunk 7 above)
Comment (nmm0) [reply src/resilience/context/MPIContext.cpp:48]: Yes, good point

File: src/resilience/context/Context.cpp (hunk 6 above)
Comment (nmm0) [reply src/resilience/context/Context.cpp:99]: e.g.

```cpp
#ifdef KR_ENABLE_MPI_CONTEXT
        {"veloc", [&]() -> std::unique_ptr<ContextBase> {
          return std::make_unique<MPIContext<VeloCMemoryBackend> >(comm, cfg);
        }},
        {"veloc-noop", [&]() -> std::unique_ptr<ContextBase> {
          return std::make_unique<MPIContext<VeloCRegisterOnlyBackend> >(comm, cfg);
        }}
#endif
```

File: src/resilience/context/Context.cpp [hunk 13]
```diff
@@ -70,7 +78,50 @@ namespace KokkosResilience
...
+  {
+    return make_context( comm, Config{ config } );
+  }
+
+  std::unique_ptr< ContextBase >
+  make_context( MPI_Comm comm, const Config &cfg )
+  {
+    using fun_type = std::function<std::unique_ptr<ContextBase>()>;
+    static std::unordered_map<std::string, fun_type> backends = {
+#ifdef KR_ENABLE_MPI_CONTEXT
```
Comment (Matthew-Whitlock) [inline src/resilience/context/Context.cpp:111]:
```suggestion
#ifdef KR_ENABLE_VELOC_BACKEND
```

**Review by Matthew-Whitlock — CHANGES_REQUESTED** [review]
One last fix I think

File: src/resilience/context/Context.cpp (hunk 13 above)
Comment (nmm0) [reply src/resilience/context/Context.cpp:111]: woops!

**Review by Matthew-Whitlock — APPROVED** [review]
